### ISSUE TITLE
No action

### ISSUE THREAD

**Issue by Shahin-rmz** [LeoWang2007/write-on-screen-anki#1]
Hello,
thanks for devloping and maintaining the Addon.
Following our [conversation](https://github.com/krassowski/Anki-TouchScreen/issues/25#issuecomment-1463517788),I tried to use it, but it seems it does not work on my device.
No action, my pen just works as it is no Addon.
![image](https://user-images.githubusercontent.com/32805117/224360237-8f1566ba-873b-4cbb-9e67-1a90e4d1cb80.png)

**Comment by LeoWang2007** [comment]
I have realized this problem. Sorry, maybe I need some time to change a solution.

**Comment by LeoWang2007** [comment]
I have fixed it!
I have tested it and it can work normally now. 
I hope you can help me test this function. 

> Click the "pen" button once to end painting and start interactive mode. 
> Click the "pen" button for the second time to enter the painting mode again. 

You can delete the plug-in and download the repaired version from the original link again.

**Comment by LeoWang2007** [comment]
Don't forget to find me here after trial. Thank you!

**Comment by Shahin-rmz** [comment]
works like a charm.
Thanks
