### ISSUE TITLE
Not Compatible with Advanced review bar.

### ISSUE THREAD

**Issue by JChatara** [LeoWang2007/write-on-screen-anki#2]
The entire bottom bar is missing now. Im assuming that it is not interacting well with the advanced review bottom bar add on (https://ankiweb.net/shared/info/1136455830) but I'm not all that tech savvy so IDK hope this helps: 
Im on anki version 2.1.49 
![image](https://user-images.githubusercontent.com/119081707/227289075-89386e04-1f07-49fe-971f-1699cecefe02.png)

Never mind! i got it to work JK

**Comment by LeoWang2007** [comment]
What’s wrong with it? Can it work now?
